import { Sparkles, BarChart2, Mail, FileText, LayoutDashboard ,Plus,Users, Home} from "lucide-react";

export const FEATURES = [
  {
    icon: Sparkles,
    title: "AI Invoice Creation",
    description:
      "Paste any text, email, or receipt, and let our AI instantly generate a complete, professional invoice for you.",
  },
  {
    icon: BarChart2,
    title: "AI-Powered Dashboard",
    description:
      "Get smart, actionable insights about your business finances, generated automatically by our AI analyst.",
  },
  {
    icon: Mail,
    title: "Smart Reminders",
    description:
      "Automatically generate polite and effective payment reminder emails for overdue invoices with a single click.",
  },
  {
    icon: FileText,
    title: "Easy Invoice Management",
    description:
      "Easily manage all your invoices, track payments, and send reminders for overdue payments.",
  },
];

export const TESTIMONIALS=[
  {
    quote: "This app saved me hours of work. I can now create and send invoices in minutes!",
    author: "Jane Doe",
    title: "Freelance Designer",
    avatar: "https://placehold.co/100x100/000000/ffffff?text=JD"
  },
  {
    quote: "The best invoicing app I have ever used. Simple, intuitive, and powerful.",
    author: "John Smith",
    title: "Small Business Owner",
    avatar: "https://placehold.co/100x100/000000/ffffff?text=JS"
  },
  {
    quote: "I love the dashboard and reporting features. It helps me keep track of my finances.",
    author: "Peter Jones",
    title: "Consultant",
    avatar: "https://placehold.co/100x100/000000/ffffff?text=PJ"
  }
]

export const FAQS = [
  {
    question: "What is the AI Invoice Generator?",
    answer:
      "The AI Invoice Generator is a smart tool that allows you to create professional invoices instantly using AI. Simply paste text, email, or receipt details, and the system will generate a complete invoice for you.",
  },
  {
    question: "Can I customize the invoices generated by AI?",
    answer:
      "Yes, all invoices generated can be customized. You can edit client details, payment terms, invoice numbers, and add your own branding before sending.",
  },
  {
    question: "How do payment reminders work?",
    answer:
      "Our AI automatically generates polite and professional payment reminders for overdue invoices. You can review them before sending, or set them to send automatically.",
  },
  {
    question: "Is my financial data secure?",
    answer:
      "Yes, we use industry-standard encryption and security practices to keep your business and client data safe.",
  },
  {
    question: "Can I track paid and unpaid invoices?",
    answer:
      "Absolutely. The dashboard shows real-time insights into your total paid, unpaid, and pending invoices, helping you stay on top of cash flow.",
  },
  {
    question: "Do I need technical knowledge to use it?",
    answer:
      "No technical knowledge is required. The interface is designed to be simple and user-friendly, so anyone can manage invoices with ease.",
  },
  {
    question: "Can I download invoices as PDF?",
    answer:
      "Yes, all invoices can be exported as professional PDF documents, ready to share or print.",
  },
];



//Navigation items configuration 
export const NAVIGATION_MENU=[
  {id:"dashboard",name:"Home",icon:Home},
  {id:"priceing",name:"Pricing",icon:LayoutDashboard},
  {id:"profile",name:"Profile",icon:Users},
  
]